"""Convert a `pip install --report` JSON report into a hash-locked
requirements file (`name==version` + `--hash=sha256:...` per package).

Used by lock-requirements.ps1; not meant to be run standalone against
arbitrary input, since it assumes every entry already carries a sha256.
"""

from __future__ import annotations

import argparse
import json
import sys


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", required=True, help="Path to a pip --report JSON file")
    parser.add_argument("--output", required=True, help="Path to write the lock file to")
    args = parser.parse_args()

    with open(args.report, encoding="utf-8") as handle:
        report = json.load(handle)

    entries: list[tuple[str, str, str]] = []
    for package in report["install"]:
        name = package["metadata"]["name"]
        version = package["metadata"]["version"]
        hashes = package["download_info"]["archive_info"]["hashes"]
        if "sha256" not in hashes:
            print(f"error: no sha256 hash available for {name}=={version}", file=sys.stderr)
            return 1
        entries.append((name, version, hashes["sha256"]))

    entries.sort(key=lambda entry: entry[0].lower())

    lines = [
        "# Hash-locked, fully-resolved transitive dependency tree for backend/requirements.txt.",
        "# Generated by scripts/lock-requirements.ps1 - do not edit by hand.",
        "# Regenerate after changing requirements.txt, then re-run the backend test suite.",
        "# Install with: pip install --require-hashes -r requirements.lock.txt",
        "",
    ]
    for name, version, sha256 in entries:
        lines.append(f"{name}=={version} \\")
        lines.append(f"    --hash=sha256:{sha256}")

    with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")

    print(f"Wrote {len(entries)} pinned packages to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
